name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install ghostscript
      run: sudo apt install ghostscript

    - name: Change ImageMagick security policy
      run: |
        DQT='"'
        SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
        RPL="rights=${DQT}read|write${DQT} pattern=${DQT}PDF${DQT}"
        sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Remove the sources directory
    - name: Remove _sources
      run: |
        rm -rf _build/html/_sources

    # Update robots.txt
    - name: Update robots.txt
      run: |
        echo -e "User-agent: *\n\nSitemap: https://jmshea.github.io/Foundations-of-Data-Science-with-Python/sitemap.xml" > _build/html/robots.txt

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html

    # Deploy the redirects to gh-pages branch
    - name: GitHub Pages action redirects
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: redirects
        keep_files: true

    # Deploy the redirects to gh-pages branch
    - name: GitHub Pages action redirects
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: data
        destination_dir: data
        keep_files: true
